orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# Set the CircleCI version.
# using 2.1 provides access to orbs and other features

version: 2.1

# basic units of work in a run
# Define the jobs we want to run for this project
jobs:
  # `build` job as entry point
  build:
    # run the steps with Docker
    docker:
      # CircleCI Node images available at: https://hub.docker.com/r/circleci/node/
      # specify the version you desire here
      - image: circleci/node:latest

      #  executor: node/default

    working_directory: ~/repo

    steps:
      # check out source code to working directory
      - checkout

      # Download and cache dependencies
      # restores saved cache if no changes are detected since last run
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: npm test

# Orchestrate our job run sequence
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master